-- ===========================================================================
-- GENERATED by scripts/gen-search-fixtures.mjs -- do not edit by hand.
--
-- Asserts that public.search_normalize() and public.search_tokens() agree with
-- lib/search.ts on every input in tests/fixtures/search-corpus.json.
--
-- The two implementations are hand-maintained mirrors of each other and
-- nothing in the build catches a divergence. This is that check. Run it
-- against any database that has the search migration applied:
--
--   psql "$DATABASE_URL" -f supabase/tests/search-normalize-parity.sql
--
-- Silence means parity. A divergence raises an exception listing every
-- mismatching row, so one run tells you the whole story rather than the first
-- failure only.
--
-- Expected values come from the TypeScript side (see search-golden.json).
-- Non-ASCII is \uXXXX-escaped so the file cannot be corrupted by an editor
-- re-encoding it.
-- ===========================================================================

do $parity$
declare
  mismatches text := '';
  failed integer := 0;
  r record;
begin
  for r in
    select *
    from (values
    (E'GrowEasy', E'groweasy', array[E'groweasy']::text[]), -- the acceptance case: stored name
    (E'grow easy', E'groweasy', array[E'grow', E'easy']::text[]), -- the acceptance case: what the user types
    (E'Grow-Easy', E'groweasy', array[E'grow', E'easy']::text[]), -- hyphen separator
    (E'grow_easy', E'groweasy', array[E'grow', E'easy']::text[]), -- underscore separator
    (E'Grow.Easy', E'groweasy', array[E'grow', E'easy']::text[]), -- dot separator
    (E'grow/easy', E'groweasy', array[E'grow', E'easy']::text[]), -- slash separator
    (E'  grow   easy  ', E'groweasy', array[E'grow', E'easy']::text[]), -- runs of whitespace, leading and trailing
    (E'', E'', '{}'::text[]), -- empty string
    (E'   ', E'', '{}'::text[]), -- whitespace only -- normalises away to nothing
    (E'-', E'', '{}'::text[]), -- separator only
    (E'!!!', E'', '{}'::text[]), -- punctuation only
    (E'AI Marketing Copilot', E'aimarketingcopilot', array[E'ai', E'marketing', E'copilot']::text[]), -- ordinary multi-token name
    (E'ZenTask', E'zentask', array[E'zentask']::text[]), -- camel case is not a token boundary
    (E'UPPERCASE', E'uppercase', array[E'uppercase']::text[]), -- case folding
    (E'MiXeDcAsE', E'mixedcase', array[E'mixedcase']::text[]), -- case folding, mixed
    (E'Caf\u00e9', E'cafe', array[E'cafe']::text[]), -- precomposed accent -- NFKD must keep the base letter
    (E'Cafe\u0301', E'cafe', array[E'cafe']::text[]), -- decomposed accent -- must equal the precomposed form
    (E'na\u00efve', E'naive', array[E'naive']::text[]), -- diaeresis
    (E'Zo\u00eb', E'zoe', array[E'zoe']::text[]), -- diaeresis, capitalised
    (E'se\u00f1or', E'senor', array[E'senor']::text[]), -- tilde
    (E'\u00c5ngstr\u00f6m', E'angstrom', array[E'angstrom']::text[]), -- ring above, plus a second accent
    (E'Stra\u00dfe', E'strae', array[E'strae']::text[]), -- sharp s -- NFKD does NOT expand it to ss
    (E'\u216b', E'xii', array[E'xii']::text[]), -- Nl roman numeral -- NFKD folds it to xii, so it survives
    (E'\u2460\u2461\u2462', E'123', '{}'::text[]), -- No circled digits -- caused a 139/140 parity failure
    (E'\u00b2', E'2', '{}'::text[]), -- No superscript -- NFKD folds to 2, so it survives normalize
    (E'\uff13', E'3', array[E'3']::text[]), -- Nd fullwidth digit -- folds to 3
    (E'\u0663', E'', '{}'::text[]), -- Nd Arabic-Indic digit -- NOT folded, so it is stripped
    (E'\u00bd', E'12', '{}'::text[]), -- vulgar fraction -- NFKD gives 1/2, slash then stripped
    (E'\ufb01le', E'file', array[E'file']::text[]), -- fi ligature -- NFKD splits it into f and i
    (E'\u33a1', E'm2', '{}'::text[]), -- squared-metre compatibility char
    (E'\u0926\u0941\u0915\u093e\u0928', E'', '{}'::text[]), -- Devanagari -- no a-z0-9 survives, normalises to empty
    (E'\u0c95\u0ca8\u0ccd\u0ca8\u0ca1', E'', '{}'::text[]), -- Kannada -- same
    (E'\u0939\u093f\u0902\u0926\u0940 Store', E'store', array[E'store']::text[]), -- mixed script -- only the Latin part survives
    (E'\u4e1c\u4eac', E'', '{}'::text[]), -- CJK -- normalises to empty
    (E'\U0001f680 Launch', E'launch', array[E'launch']::text[]), -- emoji is not a letter or digit
    (E'Product \U0001f680 Hunt', E'producthunt', array[E'product', E'hunt']::text[]), -- emoji between tokens
    (E'Product2Product', E'product2product', array[E'product2product']::text[]), -- digit inside a word
    (E'3M', E'3m', array[E'3m']::text[]), -- leading digit
    (E'v1.2.3', E'v123', array[E'v1', E'2', E'3']::text[]), -- version string
    (E'C++', E'c', array[E'c']::text[]), -- trailing symbols
    (E'AT&T', E'att', array[E'at', E't']::text[]), -- ampersand
    (E'hello@example.com', E'helloexamplecom', array[E'hello', E'example', E'com']::text[]), -- an email pasted into the search box
    (E'https://bharathunt.org/p/groweasy', E'httpsbharathuntorgpgroweasy', array[E'https', E'bharathunt', E'org', E'p', E'groweasy']::text[]), -- a URL pasted into the search box
    (E'O\'Reilly', E'oreilly', array[E'o', E'reilly']::text[]), -- apostrophe
    (E'\u201csmart quotes\u201d', E'smartquotes', array[E'smart', E'quotes']::text[]), -- typographic quotes
    (E'a\u0009b\u000ac', E'abc', array[E'a', E'b', E'c']::text[]), -- tab and newline as separators
    (E'\u00a0nbsp\u00a0', E'nbsp', array[E'nbsp']::text[]), -- non-breaking space -- NFKD folds it to a plain space
    (E'zero\u200bwidth', E'zerowidth', array[E'zero', E'width']::text[]), -- zero-width space -- stripped, so the halves join
    (E'SaaS', E'saas', array[E'saas']::text[]), -- common category term
    (E'No-Code', E'nocode', array[E'no', E'code']::text[]), -- hyphenated category term
    (E'Dev Tools', E'devtools', array[E'dev', E'tools']::text[]), -- two-word category
    (E'FinTech India', E'fintechindia', array[E'fintech', E'india']::text[]) -- domain term
    ) as t(input, want_normalized, want_tokens)
  loop
    if public.search_normalize(r.input) is distinct from r.want_normalized then
      failed := failed + 1;
      mismatches := mismatches || format(
        E'\n  search_normalize(%L)\n    want %L\n    got  %L',
        r.input, r.want_normalized, public.search_normalize(r.input)
      );
    end if;

    if public.search_tokens(r.input) is distinct from r.want_tokens then
      failed := failed + 1;
      mismatches := mismatches || format(
        E'\n  search_tokens(%L)\n    want %L\n    got  %L',
        r.input, r.want_tokens, public.search_tokens(r.input)
      );
    end if;
  end loop;

  if failed > 0 then
    raise exception
      'search normalisation parity FAILED: % mismatch(es)%',
      failed, mismatches;
  end if;

  raise notice 'search normalisation parity OK (% cases)', 52;
end
$parity$;
